### ISSUE TITLE
Script not starting when go message appears/not placing pieces after saying "first piece detected"

### ISSUE THREAD

**Issue by deadly** [jackweatherford/JstrisBot#2]
Python version: 3.10.1
Monitor resolution: 2560x1440p
Settings: all of the jstris defaults

Have tried: 
- different zooms
- modifying the script to bypass the GO! check

Picture of the page: https://gyazo.com/1f96845e59d77301b79af36d3e5a12de

**Comment by jackweatherford** [comment]
[The latest commit](https://github.com/jackweatherford/JstrisBot/commit/84c0ff8a5ea2fb52bb5ade164566d19662f15c80) implements a different ready check strategy - hopefully this resolves your issue.

Be sure to re-run `pip install -r requirements.txt` after pulling the latest commit to get the latest dependencies.
